### ISSUE TITLE
Missing file in unsupervised_TU folder

### ISSUE THREAD

**Issue by susheels** [Shen-Lab/GraphCL_Automated#1]
Hi, 
Great work and thanks for providing the code. I see that the file ``gsimclr_minmax_condition.py`` referenced in ``joaov2.sh`` is not provided in the unsupervised_TU folder. My guess is that the correct train file name has to be changed to ``joaov2.py`` inside the ``.sh`` file. Let me know if thats the case. 

Thanks

**Comment by yyou1996** [comment]
Hi @susheels,

It is the case. I have corrected it. Thanks for pointing it out!

**Comment by susheels** [comment]
Thanks, I am closing this.
